### ISSUE TITLE
import errors from vaadin-development-mode-detector

### ISSUE THREAD

**Issue by jimmont** [vaadin/vaadin-development-mode-detector#15]
After using npm/polymer build static for esm-bundled, then point imports to serve this static `build...path` and run my app:
```
Uncaught TypeError: Failed to resolve module specifier "@polymer/polymer/lib/utils/import-href.js". Relative references must start with either "/", "./", or "../".
```

```
findit -r import-href.js
finding matches in ./esm-bundled/node_modules/@vaadin/vaadin-element-mixin/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js
import { importHref } from '@polymer/polymer/lib/utils/import-href.js';
finding matches in ./esm-bundled/node_modules/@vaadin/vaadin-dropdown-menu/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js
import { importHref } from '@polymer/polymer/lib/utils/import-href.js';
finding matches in ./esm-bundled/node_modules/@vaadin/vaadin-grid/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js
import { importHref } from '@polymer/polymer/lib/utils/import-href.js';
```
is it necessary to use named imports? especially given how new and prone to error they seem to be at this point in time (in this context)?

**Comment by web-padawan** [comment]
`@vaadin/vaadin-development-mode-detector@1.0.3-pre.6` has been published earlier today and it no longer attempts to load that import (which has been removed from Polymer in 3.0.1 patch release).

Please remove your `node_modules` folder and `package-lock.json` (or `yarn.lock`, if you are using Yarn) and run `npm install` again to pick up the correct dependency. 

Apologise for the inconvenience, we should have realised this earlier. Regarding named imports, they work pretty nice, the only problem here is related to the fact that import was broken.

**Comment by jimmont** [comment]
yes, it's fixed in the update, thank you Sergey @web-padawan
