### ISSUE TITLE
Fix resources fetching on Polymer 3

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-development-mode-detector#17]
https://github.com/vaadin/vaadin-development-mode-detector/pull/16#pullrequestreview-125526687

**Comment by web-padawan** [comment]
See also https://github.com/vaadin/vaadin-development-mode-detector/tree/p3-preview-import-path
That incomplete implementation meant to be used for modulizer conversion with `--add-import-meta` flag. Hopefully I will get to it on Friday and see if it can help to get rid of 404s

**Comment by tomivirkki** [comment]
One option is to fix the path to `node_modules/...` In some environments this may cause an error...

**Comment by web-padawan** [comment]
Closing in favour of approach added in #22
