### ISSUE TITLE
Trust Flow dev mode over minification test

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-development-mode-detector#23]
With Vaadin 14, the bundle can be minified even though the app is in development mode. The logic should be changed so that if Flow is used, we trust the development mode vs production mode reported by Flow. Only in other cases should the minification test be used.

**Comment by web-padawan** [comment]
When bundle is minified, code expected to be called is stripped anyways as we are using comments now:

```  js  
/** vaadin-dev-mode:start

...

vaadin-dev-mode:end **/
```

Should we change the implementation so that webpack keeps those comments in Flow? 🤔
