### ISSUE TITLE
Ensure Polymer 3 Modulizer compatibility

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-development-mode-detector#7]
See “Generic steps” at vaadin/components-team-tasks#326

**Comment by web-padawan** [comment]
I have tried the `--add-import-path` flag, which sets the static getter on the element:
```js
  static get importPath() {
    return import.meta.url;
  }
```
As of now, this seems not to be supported by `polyserve` transform, and therefore breaks in all browsers, except for Chrome which supports it starting from the [64 stable release](https://www.chromestatus.com/feature/5637509807603712).

**Comment by web-padawan** [comment]
Closing this for now, we will have to revisit this once the `importPath` gets proper support.
